#
# Author:: Nuo Yan <nuo@opscode.com>
#
# Copyright 2010, Opscode, Inc.
#
# All rights reserved - do not redistribute
#

$KCODE= 'utf8'
require 'mixlib/localization'

module Mixlib
  module Localization
    class Messages
      
      # Retrieve the error message given the error key (e.g. 'opscode-chef-webui-nodes-403') and the language code (e.g. 'en-us')
      # returns the array of error code (customer support purpose) and the message. (e.g. ["a7svai98", "You are not authorized to view the node."])
      def self.get_message(message_key, language_code)
        message_hash = self.messages[message_key.to_s]
        begin
          [message_hash["message_id"], message_hash["languages"][language_code.to_s] || message_hash["languages"]["en_us"]]
        rescue => e
          Mixlib::Localization::Log.error("Cannot find the error message with message_key #{message_key} \n #{e.message} \n #{e.backtrace.join("\n")}")
          raise MessageRetrievalError, "Cannot find the error message with message_key '#{message_key}'."
        end
      end
      
      # Take what returns from self.get_message, and returns the formatted string.
      # Example: input: ["10000", "You are not authorized to view the node."], output: "Error 10000: You are not authorized to view the node."
      def self.parse_error_message(message_array)
        "Error #{message_array[0]}: #{message_array[1]}"
      end
      
      # Take what returns from self.get_message, and returns only the message.
      # Example: input: ["50000", "Successfully created node."], output: "Successfully created node."
      def self.parse_info_message(message_array)
        message_array[1]
      end
      
      # Generates a text file with message ids and the messages, Customer Service may use this file as a reference.
      # messages generated are not sorted (at least currently), but I don't see the need/benefits yet to make them sorted
      def self.generate_message_text_file(language, output_file)
        file = File.open(output_file, "w+")
        file.write("***Generated by rake generate_messages***\n\nID \t Message\n")
        self.messages.each_pair do |message_key, message_body|
          file.write("#{message_body["message_id"]} \t #{message_body["languages"][language] || message_body["languages"]["en_us"]} (internal key: #{message_key})\n")
        end
        file.close
      end
      
      private
      #
      # Each message is structured with 3 components:
      # 1. message_key: the string used in our code base to refer to this message (e.g. opscode-chef-webui-nodes-show-403)
      # 2. message_id: The user facing message id or error code (e.g. "10000"). It's a String, not Int.
      # 3. languages: the message in different languages, use the language code as the key.
      def self.messages
        messages = {
          "opscode-chef-webui-500" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "An application error has occurred. Please try again later.",
              "zh_cn" => "应用程序错误，请稍候重试。多谢理解。"
            }
          },
          "opscode-chef-webui-nodes-show-403" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view the node.",
              "zh_cn" => "对不起，您没有权限访问此节点。"
            }
          },
          "opscode-chef-webui-nodes-show-404" => {
            "message_id" => "10001",
            "languages" => {
              "en_us" => "Node not found.",
              "zh_cn" => "无法找到节点。"
            }
          },
          "opscode-chef-webui-nodes-show-408" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Request timed out when attempting to view the node.",
              "zh_cn" => "对不起，尝试查看节点超时。"
            }
          },
          "opscode-chef-webui-nodes-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on this node.",
              "zh_cn" => "对不起，您没有权限读取此节点的权限设置。"
            }
          },
          "opscode-chef-webui-nodes-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on this node.",
              "zh_cn" => "对不起，尝试读取节点的权限设置超时。"
            }
          },
          "opscode-chef-webui-nodes-acl-set" => {
            "message_id" => "10003",
            "languages" => {
              "en_us" => "Failed to set permissions on this node.",
              "zh_cn" => "对不起，更新此节点的权限设置失败。"
            }
          },
          "opscode-chef-webui-nodes-container-acl-get-403" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on the nodes collection in this organization.",
              "zh_cn" => "对不起，您没有权限读取此组织的节点集合的权限设置。"
            }
          },
          "opscode-chef-webui-nodes-container-acl-get-408" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on the nodes collection in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的节点集合的权限设置超时。"
            }
          },
          "opscode-chef-webui-nodes-container-acl-set" => {
            "message_id" => "10005",
            "languages" => {
              "en_us" => "Failed to set permissions on the nodes collection in this organization.",
              "zh_cn" => "对不起，更新此组织的节点集合的权限设置失败。"
            }
          },
          "opscode-chef-webui-nodes-index-403" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the nodes in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的节点列表。"
            }
          },
          "opscode-chef-webui-nodes-index-408" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of nodes in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的节点列表超时。"
            }
          },
          "opscode-chef-webui-nodes-new-403" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view roles and recipes in this organization. These objects are required to display the new node form.",
              "zh_cn" => "对不起，您没有权限查看此组织的角色和配方单，而显示新节点表单需要这些权限。"
            }
          },
          "opscode-chef-webui-nodes-new-408" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Request timed out when attempting to display the new node form.",
              "zh_cn" => "对不起，尝试显示新节点表单超时。"
            }
          },
          "opscode-chef-webui-nodes-edit-404" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Node not found.",
              "zh_cn" => "无法找到节点。"
            }
          },
          "opscode-chef-webui-nodes-edit-403" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read this node or to list the roles in this organization. These rights are required to display the node edit form.",
              "zh_cn" => "对不起，您没有权限读取此节点或角色列表，而显示编辑节点表单需要这些权限。"
            }
          },
          "opscode-chef-webui-nodes-edit-408" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the node or to list the organization's roles.",
              "zh_cn" => "对不起，尝试读取此节点或角色列表超时。"
            }
          },
          "opscode-chef-webui-nodes-create-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The node was created successfully.",
              "zh_cn" => "成功创建节点。"
            }
          },
          "opscode-chef-webui-nodes-create-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new node is not formed correctly. Check for illegal characters in the node's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新节点名字或内容中含有不支持的字符，或节点的结构不正确。"
            }
          },
          "opscode-chef-webui-nodes-create-409" => {
            "message_id" => "10010",
            "languages" => {
              "en_us" => "A node with that name already exists.",
              "zh_cn" => "同名节点已存在。"
            }
          },
          "opscode-chef-webui-nodes-create-403" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to create a node in this organization.",
              "zh_cn" => "对不起，您没有权限在此组织创建新的节点。"
            }
          },
          "opscode-chef-webui-nodes-create-408" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Request timed out when attempting to create a new node.",
              "zh_cn" => "对不起，尝试创建新节点超时。"
            }
          },
          "opscode-chef-webui-nodes-update-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The node was updated successfully.",
              "zh_cn" => "成功更新节点。"
            }
          },
          "opscode-chef-webui-nodes-update-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new node is not formed correctly. Check for illegal characters in the node's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新节点名字或内容中含有不支持的字符，或节点的结构不正确。"
            }
          },
          "opscode-chef-webui-nodes-update-403" => {
            "message_id" => "10012",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to modify this node.",
              "zh_cn" => "对不起，您没有权限修改此节点。"
            }
          },
          "opscode-chef-webui-nodes-update-408" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "Request timed out when attempting to modify the node.",
              "zh_cn" => "对不起，尝试修改此节点超时。"
            }
          },
          "opscode-chef-webui-nodes-update-409" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "The new name of the node conflicts with another existing node.",
              "zh_cn" => "同名节点已存在。"
            }
          },
          "opscode-chef-webui-nodes-update-404" => {
            "message_id" => "10014",
            "languages" => {
              "en_us" => "Node not found.",
              "zh_cn" => "无法找到节点。"
            }
          },
          "opscode-chef-webui-nodes-destroy-success" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "The node was deleted successfully.",
              "zh_cn" => "成功删除节点。"
            }
          },
          "opscode-chef-webui-nodes-destroy-confirm" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Please confirm that you would like to delete this node.",
              "zh_cn" => "请确认您希望删除此节点。"
            }
          },
          "opscode-chef-webui-nodes-destroy-404" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Node not found.",
              "zh_cn" => "无法找到节点。"
            }
          },
          "opscode-chef-webui-nodes-destroy-403" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to delete this node.",
              "zh_cn" => "对不起，您无权删除此节点。"
            }
          },
          "opscode-chef-webui-nodes-destroy-408" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Request timed out when attempting to delete this node.",
              "zh_cn" => "对不起，尝试删除此节点超时。"
            }
          },
          "opscode-chef-webui-users-index-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the users in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的用户列表。"
            }
          },
          "opscode-chef-webui-users-index-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of users in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的用户列表超时。"
            }
          },
          "opscode-chef-webui-clients-index-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the clients in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的客户端列表。"
            }
          },
          "opscode-chef-webui-clients-index-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of clients in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的客户端列表超时。"
            }
          },
          "opscode-chef-webui-groups-index-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the groups in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的群组列表。"
            }
          },
          "opscode-chef-webui-groups-index-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of groups in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的群组列表超时。"
            }
          },
          "opscode-chef-webui-groups-edit-403" => {
            "message_id" => "20001",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read this group.",
              "zh_cn" => "对不起，您没有权限读取此群组。"
            }
          },
          "opscode-chef-webui-groups-edit-404" => {
            "message_id" => "20002",
            "languages" => {
              "en_us" => "Group not found.",
              "zh_cn" => "无法找到群组。"
            }
          },
          "opscode-chef-webui-groups-edit-408" => {
            "message_id" => "20003",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the group.",
              "zh_cn" => "对不起，尝试读取此群组超时。"
            }
          },
          "opscode-chef-webui-groups-show-403" => {
            "message_id" => "30000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view the group.",
              "zh_cn" => "对不起，您没有权限访问此群组。"
            }
          },
          "opscode-chef-webui-groups-show-404" => {
            "message_id" => "30001",
            "languages" => {
              "en_us" => "Group not found.",
              "zh_cn" => "无法找到群组。"
            }
          },
          "opscode-chef-webui-groups-show-408" => {
            "message_id" => "30002",
            "languages" => {
              "en_us" => "Request timed out when attempting to view the group.",
              "zh_cn" => "对不起，尝试查看节点超时。"
            }
          },
          "opscode-chef-webui-groups-update-success" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The group was updated successfully.",
              "zh_cn" => "成功更新群组。"
            }
          },
          "opscode-chef-webui-groups-update-failed-validation" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The new group name contains illegal characters. The following characters are allowed: a-z, 0-9, _, -",
              "zh_cn" => "新群组名字中含有不支持的字符。系统支持的字符包括：a-z, 0-9, _, -。"
            }
          },
          "opscode-chef-webui-groups-update-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to modify this group.",
              "zh_cn" => "对不起，您没有权限修改此群组。"
            }
          },
          "opscode-chef-webui-groups-update-404" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Group not found.",
              "zh_cn" => "无法找到群组。"
            }
          },
          "opscode-chef-webui-groups-update-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to modify the group.",
              "zh_cn" => "对不起，尝试修改此群组超时。"
            }
          },
          "opscode-chef-webui-groups-update-409" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The new name of the group conflicts with another existing group.",
              "zh_cn" => "同名群组已存在。"
            }
          },
          "opscode-chef-webui-groups-create-success" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The group was created successfully.",
              "zh_cn" => "成功创建群组。"
            }
          },
          "opscode-chef-webui-groups-create-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to create a group in this organization.",
              "zh_cn" => "对不起，您没有权限在此组织创建新的群组。"
            }
          },
          "opscode-chef-webui-groups-create-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to create a new group.",
              "zh_cn" => "对不起，尝试创建新群组超时。"
            }
          },
          "opscode-chef-webui-groups-create-409" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "A group with that name already exists.",
              "zh_cn" => "同名群组已存在。"
            }
          },
          "opscode-chef-webui-groups-create-failed-validation" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The new group name contains illegal characters. The following characters are allowed: a-z, 0-9, _, -",
              "zh_cn" => "新群组名字中含有不支持的字符。系统支持的字符包括：a-z, 0-9, _, -。"
            }
          },
          "opscode-chef-webui-groups-destroy-default-groups" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Deleting the following groups is prohibited: admins, users, and clients.",
              "zh_cn" => "无法删除系统内建群组：admins，users，和clients。"
            }
          },
          "opscode-chef-webui-groups-destroy-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to delete this group.",
              "zh_cn" => "对不起，您没有权限删除此群组。"
            }
          },
          "opscode-chef-webui-groups-destroy-404" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Group not found.",
              "zh_cn" => "无法找到群组。"
            }
          },
          "opscode-chef-webui-groups-destroy-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to delete this group.",
              "zh_cn" => "对不起，尝试删除此群组超时。"
            }
          },
          "opscode-chef-webui-groups-destroy-success" => {
		  
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The group was deleted successfully.",
              "zh_cn" => "成功删除群组。"
            }
          },
          "opscode-chef-webui-groups-destroy-confirm" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Please confirm that you would like to delete this group.",
              "zh_cn" => "请确认您希望删除此群组。"
            }
          },
          "opscode-chef-webui-groups-acl-set" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Failed to set permissions on this group.",
              "zh_cn" => "对不起，更新此群组的权限设置失败。"
            }
          },
          "opscode-chef-webui-groups-container-acl-get-403" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on the groups collection in this organization.",
              "zh_cn" => "对不起，您没有权限读取此组织的群组集合的权限设置。"
            }
          },
          "opscode-chef-webui-groups-container-acl-get-408" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on the groups collection in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的群组集合的权限设置超时。"
            }
          },
          "opscode-chef-webui-groups-container-acl-set" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "Failed to set permissions on the groups collection in this organization.",
              "zh_cn" => "对不起，更新此组织的群组集合的权限设置失败。"
            }
          },
          "opscode-chef-webui-groups-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on this group.",
              "zh_cn" => "对不起，您没有权限读取此群组的权限设置。"
            }
          },
          "opscode-chef-webui-groups-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on this group.",
              "zh_cn" => "对不起，尝试读取群组的权限设置超时"
            }
          },
          "opscode-chef-webui-cookbooks-index-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the cookbooks in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的食谱列表。"
            }
          },
          "opscode-chef-webui-cookbooks-index-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of cookbooks in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的食谱列表超时。"
            }
          },
          "opscode-chef-webui-cookbooks-show-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view the cookbook.",
              "zh_cn" => "对不起，您没有权限查看此食谱。"
            }
          },
          "opscode-chef-webui-cookbooks-show-404" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Cookbook not found.",
              "zh_cn" => "无法找到食谱。"
            }
          },
          "opscode-chef-webui-cookbooks-show-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to view the cookbook.",
              "zh_cn" => "对不起，尝试查看食谱超时。"
            }
          },
          "opscode-chef-webui-cookbooks-container-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on the cookbooks collection in this organization.",
              "zh_cn" => "对不起，您没有权限读取此组织的食谱集合的权限设置。"
            }
          },
          "opscode-chef-webui-cookbooks-container-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on the cookbooks collection in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的食谱集合的权限设置超时。"
            }
          },
          "opscode-chef-webui-cookbooks-container-acl-set" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Failed to set permissions on the cookbooks collection in this organization.",
              "zh_cn" => "对不起，更新此组织的食谱集合权限设置失败。"
            }
          },
          "opscode-chef-webui-cookbooks-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on this cookbook.",
              "zh_cn" => "对不起，您没有权限读取此食谱的权限设置。"
            }
          },
          "opscode-chef-webui-cookbooks-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on this cookbook.",
              "zh_cn" => "对不起，常试读去食谱的权限设置超时。"
            }
          },
          "opscode-chef-webui-cookbooks-acl-set" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Failed to set permissions on this cookbook.",
              "zh_cn" => "对不起，更新此食谱的权限设置失败。"
            }
          },
		  "opscode-chef-webui-roles-show-403" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view the role.",
              "zh_cn" => "对不起，您没有权限访问此角色。"
            }
          },
          "opscode-chef-webui-roles-show-404" => {
            "message_id" => "10001",
            "languages" => {
              "en_us" => "role not found.",
              "zh_cn" => "无法找到角色。"
            }
          },
          "opscode-chef-webui-roles-show-408" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Request timed out when attempting to view the role.",
              "zh_cn" => "对不起，尝试查看角色超时。"
            }
          },
          "opscode-chef-webui-roles-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on this role.",
              "zh_cn" => "对不起，您没有权限读取此角色的权限设置。"
            }
          },
          "opscode-chef-webui-roles-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on this role.",
              "zh_cn" => "对不起，尝试读取角色的权限设置超时。"
            }
          },
          "opscode-chef-webui-roles-acl-set" => {
            "message_id" => "10003",
            "languages" => {
              "en_us" => "Failed to set permissions on this role.",
              "zh_cn" => "对不起，更新此角色的权限设置失败。"
            }
          },
          "opscode-chef-webui-roles-container-acl-get-403" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on the roles collection in this organization.",
              "zh_cn" => "对不起，您没有权限读取此组织的角色集合的权限设置。"
            }
          },
          "opscode-chef-webui-roles-container-acl-get-408" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on the roles collection in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的角色集合的权限设置超时。"
            }
          },
          "opscode-chef-webui-roles-container-acl-set" => {
            "message_id" => "10005",
            "languages" => {
              "en_us" => "Failed to set permissions on the roles collection in this organization.",
              "zh_cn" => "对不起，更新此组织的角色集合的权限设置失败。"
            }
          },
          "opscode-chef-webui-roles-index-403" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the roles in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的角色列表。"
            }
          },
          "opscode-chef-webui-roles-index-408" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of roles in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的角色列表超时。"
            }
          },
          "opscode-chef-webui-roles-new-403" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view roles and recipes in this organization. These objects are required to display the new role form.",
              "zh_cn" => "对不起，您没有权限查看此组织的角色和配方单，而显示新角色表单需要这些权限。"
            }
          },
          "opscode-chef-webui-roles-new-408" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Request timed out when attempting to display the new role form.",
              "zh_cn" => "对不起，尝试显示新角色表单超时。"
            }
          },
          "opscode-chef-webui-roles-edit-404" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "role not found.",
              "zh_cn" => "无法找到角色。"
            }
          },
          "opscode-chef-webui-roles-edit-403" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read this role or to list the roles in this organization. These rights are required to display the role edit form.",
              "zh_cn" => "对不起，您没有权限读取此角色或角色列表，而显示编辑角色表单需要这些权限。"
            }
          },
          "opscode-chef-webui-roles-edit-408" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the role or to list the organization's roles.",
              "zh_cn" => "对不起，尝试读取此角色或角色列表超时。"
            }
          },
          "opscode-chef-webui-roles-create-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The role was created successfully.",
              "zh_cn" => "成功创建角色。"
            }
          },
          "opscode-chef-webui-roles-create-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new role is not formed correctly. Check for illegal characters in the role's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新角色名字或内容中含有不支持的字符，或角色的结构不正确。"
            }
          },
          "opscode-chef-webui-roles-create-409" => {
            "message_id" => "10010",
            "languages" => {
              "en_us" => "A role with that name already exists.",
              "zh_cn" => "同名角色已存在。"
            }
          },
          "opscode-chef-webui-roles-create-403" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to create a role in this organization.",
              "zh_cn" => "对不起，您没有权限在此组织创建新的角色。"
            }
          },
          "opscode-chef-webui-roles-create-408" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Request timed out when attempting to create a new role.",
              "zh_cn" => "对不起，尝试创建新角色超时。"
            }
          },
          "opscode-chef-webui-roles-update-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The role was updated successfully.",
              "zh_cn" => "成功更新角色。"
            }
          },
          "opscode-chef-webui-roles-update-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new role is not formed correctly. Check for illegal characters in the role's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新角色名字或内容中含有不支持的字符，或角色的结构不正确。"
            }
          },
          "opscode-chef-webui-roles-update-403" => {
            "message_id" => "10012",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to modify this role.",
              "zh_cn" => "对不起，您没有权限修改此角色。"
            }
          },
          "opscode-chef-webui-roles-update-408" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "Request timed out when attempting to modify the role.",
              "zh_cn" => "对不起，尝试修改此角色超时。"
            }
          },
          "opscode-chef-webui-roles-update-409" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "The new name of the role conflicts with another existing role.",
              "zh_cn" => "同名角色已存在。"
            }
          },
          "opscode-chef-webui-roles-update-404" => {
            "message_id" => "10014",
            "languages" => {
              "en_us" => "role not found.",
              "zh_cn" => "无法找到角色。"
            }
          },
          "opscode-chef-webui-roles-destroy-success" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "The role was deleted successfully.",
              "zh_cn" => "成功删除角色。"
            }
          },
          "opscode-chef-webui-roles-destroy-confirm" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Please confirm that you would like to delete this role.",
              "zh_cn" => "请确认您希望删除此角色。"
            }
          },
          "opscode-chef-webui-roles-destroy-404" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "role not found.",
              "zh_cn" => "无法找到角色。"
            }
          },
          "opscode-chef-webui-roles-destroy-403" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to delete this role.",
              "zh_cn" => "对不起，您无权删除此角色。"
            }
          },
          "opscode-chef-webui-role-destroy-408" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Request timed out when attempting to delete this role.",
              "zh_cn" => "对不起，尝试删除此角色超时。"
            }
          },
		            "opscode-chef-webui-databags-show-403" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view the databag.",
              "zh_cn" => "对不起，您没有权限访问此数据包。"
            }
          },
          "opscode-chef-webui-databags-show-404" => {
            "message_id" => "10001",
            "languages" => {
              "en_us" => "databag not found.",
              "zh_cn" => "无法找到数据包。"
            }
          },
          "opscode-chef-webui-databags-show-408" => {
            "message_id" => "10000",
            "languages" => {
              "en_us" => "Request timed out when attempting to view the databag.",
              "zh_cn" => "对不起，尝试查看数据包超时。"
            }
          },
          "opscode-chef-webui-databags-acl-get-403" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on this databag.",
              "zh_cn" => "对不起，您没有权限读取此数据包的权限设置。"
            }
          },
          "opscode-chef-webui-databags-acl-get-408" => {
            "message_id" => "10002",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on this databag.",
              "zh_cn" => "对不起，尝试读取数据包的权限设置超时。"
            }
          },
          "opscode-chef-webui-databags-acl-set" => {
            "message_id" => "10003",
            "languages" => {
              "en_us" => "Failed to set permissions on this databag.",
              "zh_cn" => "对不起，更新此数据包的权限设置失败。"
            }
          },
          "opscode-chef-webui-databags-container-acl-get-403" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read the permissions on the databags collection in this organization.",
              "zh_cn" => "对不起，您没有权限读取此组织的数据包集合的权限设置。"
            }
          },
          "opscode-chef-webui-databags-container-acl-get-408" => {
            "message_id" => "10004",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the permissions on the databags collection in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的数据包集合的权限设置超时。"
            }
          },
          "opscode-chef-webui-databags-container-acl-set" => {
            "message_id" => "10005",
            "languages" => {
              "en_us" => "Failed to set permissions on the databags collection in this organization.",
              "zh_cn" => "对不起，更新此组织的数据包集合的权限设置失败。"
            }
          },
          "opscode-chef-webui-databags-index-403" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to list the databags in this organization.",
              "zh_cn" => "对不起，您没有权限查看此组织的数据包列表。"
            }
          },
          "opscode-chef-webui-databags-index-408" => {
            "message_id" => "10006",
            "languages" => {
              "en_us" => "Request timed out when attempting to retrieve the list of databags in this organization.",
              "zh_cn" => "对不起，尝试读取此组织的数据包列表超时。"
            }
          },
          "opscode-chef-webui-databags-new-403" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to view databags and recipes in this organization. These objects are required to display the new databag form.",
              "zh_cn" => "对不起，您没有权限查看此组织的数据包和菜谱，而显示新数据包表单需要这些权限。"
            }
          },
          "opscode-chef-webui-databags-new-408" => {
            "message_id" => "10007",
            "languages" => {
              "en_us" => "Request timed out when attempting to display the new databag form.",
              "zh_cn" => "对不起，尝试显示新数据包表单超时。"
            }
          },
          "opscode-chef-webui-databags-edit-404" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "databag not found.",
              "zh_cn" => "无法找到数据包。"
            }
          },
          "opscode-chef-webui-databags-edit-403" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to read this databag or to list the databags in this organization. These rights are required to display the databag edit form.",
              "zh_cn" => "对不起，您没有权限读取此数据包或数据包列表，而显示编辑数据包表单需要这些权限。"
            }
          },
          "opscode-chef-webui-databags-edit-408" => {
            "message_id" => "10008",
            "languages" => {
              "en_us" => "Request timed out when attempting to read the databag or to list the organization's databags.",
              "zh_cn" => "对不起，尝试读取此数据包或数据包列表超时。"
            }
          },
          "opscode-chef-webui-databags-create-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The databag was created successfully.",
              "zh_cn" => "成功创建数据包。"
            }
          },
          "opscode-chef-webui-databags-create-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new databag is not formed correctly. Check for illegal characters in the databag's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新数据包名字或内容中含有不支持的字符，或数据包的结构不正确。"
            }
          },
          "opscode-chef-webui-databags-create-409" => {
            "message_id" => "10010",
            "languages" => {
              "en_us" => "A databag with that name already exists.",
              "zh_cn" => "同名数据包已存在。"
            }
          },
          "opscode-chef-webui-databags-create-403" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to create a databag in this organization.",
              "zh_cn" => "对不起，您没有权限在此组织创建新的数据包。"
            }
          },
          "opscode-chef-webui-databags-create-408" => {
            "message_id" => "10011",
            "languages" => {
              "en_us" => "Request timed out when attempting to create a new databag.",
              "zh_cn" => "对不起，尝试创建新数据包超时。"
            }
          },
          "opscode-chef-webui-databags-update-success" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The databag was updated successfully.",
              "zh_cn" => "成功更新数据包。"
            }
          },
          "opscode-chef-webui-databags-update-failed-validation" => {
            "message_id" => "10009",
            "languages" => {
              "en_us" => "The new databag is not formed correctly. Check for illegal characters in the databag's name or body, and check that the body is formed correctly.",
              "zh_cn" => "新数据包名字或内容中含有不支持的字符，或数据包的结构不正确。"
            }
          },
          "opscode-chef-webui-databags-update-403" => {
            "message_id" => "10012",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to modify this databag.",
              "zh_cn" => "对不起，您没有权限修改此数据包。"
            }
          },
          "opscode-chef-webui-databags-update-408" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "Request timed out when attempting to modify the databag.",
              "zh_cn" => "对不起，尝试修改此数据包超时。"
            }
          },
          "opscode-chef-webui-databags-update-409" => {
            "message_id" => "10013",
            "languages" => {
              "en_us" => "The new name of the databag conflicts with another existing databag.",
              "zh_cn" => "同名数据包已存在。"
            }
          },
          "opscode-chef-webui-databags-update-404" => {
            "message_id" => "10014",
            "languages" => {
              "en_us" => "databag not found.",
              "zh_cn" => "无法找到数据包。"
            }
          },
          "opscode-chef-webui-databags-destroy-success" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "The databag was deleted successfully.",
              "zh_cn" => "成功删除数据包。"
            }
          },
          "opscode-chef-webui-databags-destroy-confirm" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Please confirm that you would like to delete this databag.",
              "zh_cn" => "请确认您希望删除此数据包。"
            }
          },
          "opscode-chef-webui-databags-destroy-404" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "databag not found.",
              "zh_cn" => "无法找到数据包。"
            }
          },
          "opscode-chef-webui-databags-destroy-403" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Permission denied. You do not have permission to delete this databag.",
              "zh_cn" => "对不起，您无权删除此数据包。"
            }
          },
          "opscode-chef-webui-databag-destroy-408" => {
            "message_id" => "10015",
            "languages" => {
              "en_us" => "Request timed out when attempting to delete this databag.",
              "zh_cn" => "对不起，尝试删除此数据包超时。"
            }
          },
          "opscode-chef-webui-application-acl-set-success" => {
            "message_id" => "20000",
            "languages" => {
              "en_us" => "The permissions were updated successfully.",
              "zh_cn" => "成功更新权限设置。"
            }
          }
        }
      end
    end
  end
end